// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitCatShigavkp.Data;

#nullable disable

namespace RecruitCatShigavkp.Migrations
{
    [DbContext(typeof(RecruitCatShigavkpContext))]
    [Migration("20220919182222_Candidates2")]
    partial class Candidates2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecruitCatShigavkp.Models.Candidate", b =>
                {
                    b.Property<int>("candidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("candidateId"), 1L, 1);

                    b.Property<string>("candidateFname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("candidateLname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("companyId")
                        .HasColumnType("int");

                    b.Property<string>("emailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("industryId")
                        .HasColumnType("int");

                    b.Property<int?>("jobtitleId")
                        .HasColumnType("int");

                    b.Property<string>("mobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("targetSalary")
                        .HasColumnType("int");

                    b.HasKey("candidateId");

                    b.HasIndex("companyId");

                    b.HasIndex("industryId");

                    b.HasIndex("jobtitleId");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("RecruitCatShigavkp.Models.Company", b =>
                {
                    b.Property<int>("companyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("companyId"), 1L, 1);

                    b.Property<string>("companyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyRank")
                        .HasColumnType("int");

                    b.Property<int?>("industryId")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("max_salary")
                        .HasColumnType("int");

                    b.Property<int>("min_salary")
                        .HasColumnType("int");

                    b.Property<string>("position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("datetime2");

                    b.HasKey("companyId");

                    b.HasIndex("industryId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("RecruitCatShigavkp.Models.Industry", b =>
                {
                    b.Property<int>("industryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("industryId"), 1L, 1);

                    b.Property<string>("industryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("industryType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("industryId");

                    b.ToTable("Industry");
                });

            modelBuilder.Entity("RecruitCatShigavkp.Models.Jobtitle", b =>
                {
                    b.Property<int>("jobtitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("jobtitleId"), 1L, 1);

                    b.Property<DateTime?>("deadLine")
                        .HasColumnType("datetime2");

                    b.Property<string>("jobType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maxSalary")
                        .HasColumnType("int");

                    b.Property<int>("minSalary")
                        .HasColumnType("int");

                    b.Property<string>("skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("jobtitleId");

                    b.ToTable("Jobtitle");
                });

            modelBuilder.Entity("RecruitCatShigavkp.Models.Candidate", b =>
                {
                    b.HasOne("RecruitCatShigavkp.Models.Company", "Company")
                        .WithMany("Candidates")
                        .HasForeignKey("companyId");

                    b.HasOne("RecruitCatShigavkp.Models.Industry", "Industry")
                        .WithMany("Candidate")
                        .HasForeignKey("industryId");

                    b.HasOne("RecruitCatShigavkp.Models.Jobtitle", "Jobtitle")
                        .WithMany("Candidate")
                        .HasForeignKey("jobtitleId");

                    b.Navigation("Company");

                    b.Navigation("Industry");

                    b.Navigation("Jobtitle");
                });

            modelBuilder.Entity("RecruitCatShigavkp.Models.Company", b =>
                {
                    b.HasOne("RecruitCatShigavkp.Models.Industry", "Industry")
                        .WithMany("Company")
                        .HasForeignKey("industryId");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("RecruitCatShigavkp.Models.Company", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("RecruitCatShigavkp.Models.Industry", b =>
                {
                    b.Navigation("Candidate");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitCatShigavkp.Models.Jobtitle", b =>
                {
                    b.Navigation("Candidate");
                });
#pragma warning restore 612, 618
        }
    }
}
